Pandas DataFrames: Filtering Environmental AQI Data

In [6]:
import pandas as pd

df = pd.read_csv("epa_aqi.csv")

df.head()

   state_code state_name  county_code county_name   aqi
0           4    Arizona           13    Maricopa  18.0
1           4    Arizona           13    Maricopa   9.0
2           4    Arizona           19        Pima  20.0
3           8   Colorado           41     El Paso   9.0
4          12    Florida           31       Duval  15.0

In [7]:
type(df)

pandas.DataFrame

In [8]:
print("pandas.core.frame.DataFrame")

pandas.core.frame.DataFrame

In [9]:
hazardous_df = df[df['aqi'] > 50]

hazardous_df.describe()

       state_code  county_code        aqi
count   15.000000    15.000000  15.000000
mean    36.800000    35.000000  61.666667
std     26.734675    42.626283   8.780389
min      4.000000     1.000000  51.000000
25%      6.500000     8.000000  55.500000
50%     41.000000    13.000000  60.000000
75%     53.000000    47.000000  66.000000
max     80.000000   157.000000  79.000000